PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX nbf:	<http://ldf.fi/nbf/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX relse: <http://ldf.fi/relse/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gvp: <http://vocab.getty.edu/ontology#>
BASE <http://ldf.fi/relse/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
  ?relPerson a schema:Person ;
    skos:prefLabel ?label ;
    owl:sameAs ?person ;
    foaf:focus ?focus ;
    schema:relatedLink ?relatedLink .
}
WHERE {
  ?relPerson a schema:Person .
  ?relPerson skos:prefLabel ?label .
  ?relPerson owl:sameAs ?person .
  ?person foaf:focus ?focus .
  ?person schema:relatedLink ?relatedLink .
  ?focus nbf:sukupuoli ?gender .
  FILTER(str(?gender) != "pariskunta")
  ?death crm:P100_was_death_of ?focus .
  ?death nbf:time ?deathTime .
}
