PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX nbf:	<http://ldf.fi/nbf/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX relse: <http://ldf.fi/relse/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
BASE <http://ldf.fi/relse/>

CONSTRUCT {
  ?uri a relse:Relation ;
    relse:personSubject ?person ;
    relse:placeObject ?place ;
    skos:prefLabel ?description ;
    relse:relationType relse:literaryWorkDepictsPlace ;
    relse:source ?source ;
    relse:date ?date ;
    relse:sourceName "Kirjan tiedot Kansalliskirjaston tietokannassa"@fi ;
    relse:sourceLink ?source ;
    
}
WHERE {
  ?relation a relse:Relation .
  ?relation relse:source ?source .
  ?relation relse:personSubject ?subject .
  ?relation relse:placeObject ?object .
  ?relation relse:entityName ?workName .
  ?person skos:exactMatch ?subject .
  ?place skos:exactMatch ?object .
  ?place skos:prefLabel ?placeName .
  
  BIND(concat(substr(?workName, 1, 60), "...") AS ?shortName) .
  BIND(IF(strlen(?workName) < 60, ?workName, ?shortName)  AS ?shortenedName) .
  
  ?person skosxl:prefLabel ?personLabel .
  ?personLabel schema:familyName ?familyName .
  ?personLabel schema:givenName ?givenName .
  
  BIND(uri(encode_for_uri(concat(str(?person), str(?place), str(?source), "work_depicts"))) as ?uri) .
  BIND(concat(str(?givenName), " ", str(?familyName), " on merkitty tekijäksi kirjalliseen teokseen '", str(?shortenedName), "' joka kuvaa paikkaa ", str(?placeName), ".") as ?description) .
}
