PREFIX yso: <http://www.yso.fi/onto/yso/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX relse: <http://ldf.fi/relsearch/>

CONSTRUCT {
  [ a relse:Relation ;
      relse:personSubject ?author ;
      relse:placeObject ?place ;
      relse:entityName ?workName ;
      relse:source ?work ;
      relse:sourceLink ?uri ;
      relse:relationType relse:literalWorkDepictsPlace ;
  ]
}
WHERE {
  ?work schema:author ?author .
  ?place skos:inScheme yso:places .
  ?work schema:about ?place .
  FILTER (?place != yso:p94426) . # not including Finland
  ?work schema:name ?workName .
}
