PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX yso: <http://www.yso.fi/onto/yso/>
PREFIX relse: <http://ldf.fi/relse/>

CONSTRUCT {
  [ a relse:Relation ;
      relse:personSubject ?author ;
      relse:placeObject ?place ;
      relse:entityName ?singleWorkName ;
      relse:source ?work ;
      relse:sourceLink ?uri ;
      relse:relationType relse:literalWorkDepictsPlace ;
  ]
}
WHERE {
    SELECT DISTINCT ?author ?work ?uri ?place (sample(?workName) as ?singleWorkName)
    WHERE {
  		?work schema:author ?author .
  		?place skos:inScheme yso:places .
  		?work schema:about ?place .
  		FILTER (?place != yso:p94426) . # not including Finland
  		?work schema:name ?workName .
	} GROUP BY ?author ?work ?uri ?place
}
