PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
    
SELECT ?eLabel ?personLabel ?any ?placeName 
WHERE {
  ?event a crm:E5_Event .
  ?event crm:P7_took_place_at ?place .
  ?place rdfs:label ?placeName .
  FILTER (lang(?placeName) = 'fi') .
  ?event crm:P11_had_participant ?participant .
  ?event rdfs:label ?eLabel .
  ?participant rdfs:label ?personLabel .
}
LIMIT 10
